name: spoonacular
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  material_design_icons_flutter:
  flutter:
    sdk: flutter 

  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2
  flutter_auth_buttons: ^0.10.0
  google_sign_in: ^4.5.5
  provider: ^4.3.2+2
  
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  http:
  shared_preferences:
  translator:
  rxdart: ^0.24.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - images/aguacate.jpg
    - images/leckerbrot.jpg
    - images/lupito.jpg
    - images/manadeoscileos.jpg
    - images/ventanita.jpg
    - images/wellness.jpg
    - images/icon-no-gluten.png
    - images/icon-vegetarian.png
    - images/icon-omnivoro.png
    - images/icon-vegan.png
    - images/dish1.png
    - images/dish2.png
    - images/dish3.png
    - images/dish4.png
    - images/arbeja.png
    - images/arroz.png
    - images/cebolla.png
    - images/fideo.png
    - images/lechuga.png
    - images/tomate.png
    - images/zanahoria.png
    - images/logo.png
    - images/loading-circle.gif

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Pacifico
      fonts:
       - asset: fonts/Pacifico.ttf
    - family: Muli
      fonts:
      - asset: fonts/Muli.ttf
    - family: Rubik
      fonts:
      - asset: fonts/Rubik-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
